### ISSUE TITLE
关于标签页

### ISSUE THREAD

**Issue by perhaps542** [YangDejie/yangdejie.github.io#1]
实在不好意思，因为是在学习的小白，所以看了挺久没看明白标签页的内容如何写成您现在这样。求指教。

**Comment by YangDejie** [comment]
关于标签页的生成在[ themes](https://github.com/YangDejie/yangdejie.github.io/tree/feature/theme) 分支上https://github.com/YangDejie/yangdejie.github.io/blob/feature/theme/layout/tag.ejs
